// Autogenerated by the Boron compiler
// Version 0.1.0
// Created on 2022/07/06 at 13:04:18 local time


#include <stdio.h>
#include <stdbool.h>

int main(void) {
	int x = 0;
	while (x < 10) {
printf("%d\n", x);
};
}
