// Autogenerated by the Boron compiler
// Version 0.1.0
// Created on 2022/07/06 at 12:21:32 local time


#include <stdio.h>
#include <stdbool.h>

int main(void) {
	int x = 3 + 3;
	x = x + 1;
	printf("%d\n", x);
}
