// Autogenerated by the Boron compiler
// Version 0.13.1
// Created on 2022/07/09 at 12:42:36 local time


#include <stdio.h>
#include <stdbool.h>

int main(void) {
int w = (a + (b ? !c : -d));
int x = ((3 < 2) ? 0 : 1);
int y = 0;
int z = 0;
int count = 0;
while (count <= 10) {
z = (x + y);
printf("%d\n", z);
x = y;
y = z;
count = (count + 1);
}
return 0;
}
