// Library autogenerated by the Boron compiler
// Version 0.24.0
// Created on 2022/07/13 at 14:28:30 local time

#ifndef MIN
#define MIN

#include <stdio.h>
#include <stdbool.h>



int min(int x, int y) {
if ((x < y)) {
return x;
} else {
return y;
}
}

#endif
